
title: Udey Rishi
url: 'https://www.udey.dev'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Udey Rishi
tagline: Sofware Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: me@udey.dev
# phone: 012 345 6789
website: www.udey.dev
linkedin: udeyrishi
github: udeyrishi
twitter: '@udeyrishi'
